# Generated by Django 5.2.4 on 2025-08-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportetragamonedas',
            name='firma_cajero',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Firma del Cajero'),
        ),
        migrations.AddField(
            model_name='reportetragamonedas',
            name='firma_encargado_sala',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Firma del Encargado de Sala'),
        ),
        migrations.AddField(
            model_name='reportetragamonedas',
            name='firma_jefe_slot',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Firma del Jefe de Slot'),
        ),
        migrations.AddField(
            model_name='reportetragamonedas',
            name='firma_tecnico',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Firma del Técnico'),
        ),
    ]
