# Generated by Django 5.1.3 on 2025-08-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reports",
            "0003_alter_reportetragamonedas_att_paid_total_won_cierre_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportetragamonedas",
            name="fecha_cierre",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
