# Generated by Django 5.2.5 on 2025-08-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0004_alter_reportetragamonedas_fecha_cierre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportetragamonedas",
            name="fecha_inicio",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reportetragamonedas",
            name="marca_juego",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="reportetragamonedas",
            name="modelo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="reportetragamonedas",
            name="numero_maquina",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="reportetragamonedas",
            name="serie",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
