# Generated by Django 5.2.5 on 2025-08-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0005_alter_reportetragamonedas_fecha_inicio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportetragamonedas",
            name="att_paid_total_won_cierre",
            field=models.TextField(verbose_name="ATT PAID TOTAL WON (Cierre)"),
        ),
        migrations.AlterField(
            model_name="reportetragamonedas",
            name="att_paid_total_won_inicio",
            field=models.TextField(verbose_name="ATT PAID TOTAL WON (Inicio)"),
        ),
        migrations.AlterField(
            model_name="reportetragamonedas",
            name="billetes_cierre",
            field=models.TextField(verbose_name="Billetes (Cierre)"),
        ),
        migrations.AlterField(
            model_name="reportetragamonedas",
            name="billetes_inicio",
            field=models.TextField(verbose_name="Billetes (Inicio)"),
        ),
        migrations.AlterField(
            model_name="reportetragamonedas",
            name="creditos_cancelados_cierre",
            field=models.TextField(verbose_name="Créditos Cancelados (Cierre)"),
        ),
        migrations.AlterField(
            model_name="reportetragamonedas",
            name="creditos_cancelados_inicio",
            field=models.TextField(verbose_name="Créditos Cancelados (Inicio)"),
        ),
        migrations.AlterField(
            model_name="reportetragamonedas",
            name="creditos_cancelados_totales_cierre",
            field=models.TextField(verbose_name="Créditos Cancelados Totales (Cierre)"),
        ),
        migrations.AlterField(
            model_name="reportetragamonedas",
            name="creditos_cancelados_totales_inicio",
            field=models.TextField(verbose_name="Créditos Cancelados Totales (Inicio)"),
        ),
        migrations.AlterField(
            model_name="reportetragamonedas",
            name="creditos_jugados_cierre",
            field=models.TextField(verbose_name="Créditos Jugados (Cierre)"),
        ),
        migrations.AlterField(
            model_name="reportetragamonedas",
            name="creditos_jugados_inicio",
            field=models.TextField(verbose_name="Créditos Jugados (Inicio)"),
        ),
        migrations.AlterField(
            model_name="reportetragamonedas",
            name="creditos_pagados_cierre",
            field=models.TextField(verbose_name="Créditos Pagados (Cierre)"),
        ),
        migrations.AlterField(
            model_name="reportetragamonedas",
            name="creditos_pagados_inicio",
            field=models.TextField(verbose_name="Créditos Pagados (Inicio)"),
        ),
        migrations.AlterField(
            model_name="reportetragamonedas",
            name="drop_cierre",
            field=models.TextField(verbose_name="Drop (Cierre)"),
        ),
        migrations.AlterField(
            model_name="reportetragamonedas",
            name="drop_inicio",
            field=models.TextField(verbose_name="Drop (Inicio)"),
        ),
        migrations.AlterField(
            model_name="reportetragamonedas",
            name="jackpot_cierre",
            field=models.TextField(verbose_name="Jackpot (Cierre)"),
        ),
        migrations.AlterField(
            model_name="reportetragamonedas",
            name="jackpot_inicio",
            field=models.TextField(verbose_name="Jackpot (Inicio)"),
        ),
        migrations.AlterField(
            model_name="reportetragamonedas",
            name="juegos_cierre",
            field=models.TextField(verbose_name="Juegos (Cierre)"),
        ),
        migrations.AlterField(
            model_name="reportetragamonedas",
            name="juegos_inicio",
            field=models.TextField(verbose_name="Juegos (Inicio)"),
        ),
        migrations.AlterField(
            model_name="reportetragamonedas",
            name="porcentaje_real_cierre",
            field=models.TextField(verbose_name="% Real (Cierre)"),
        ),
        migrations.AlterField(
            model_name="reportetragamonedas",
            name="porcentaje_real_inicio",
            field=models.TextField(verbose_name="% Real (Inicio)"),
        ),
        migrations.AlterField(
            model_name="reportetragamonedas",
            name="valor_de_credito_cierre",
            field=models.TextField(verbose_name="Valor de Crédito (Cierre)"),
        ),
        migrations.AlterField(
            model_name="reportetragamonedas",
            name="valor_de_credito_inicio",
            field=models.TextField(verbose_name="Valor de Crédito (Inicio)"),
        ),
        migrations.AlterField(
            model_name="reportetragamonedas",
            name="valor_transmision_cierre",
            field=models.TextField(verbose_name="Valor de Transmisión (Cierre)"),
        ),
        migrations.AlterField(
            model_name="reportetragamonedas",
            name="valor_transmision_inicio",
            field=models.TextField(verbose_name="Valor de Transmisión (Inicio)"),
        ),
        migrations.AlterField(
            model_name="reportetragamonedas",
            name="voucher_in_cierre",
            field=models.TextField(verbose_name="Voucher In (Cierre)"),
        ),
        migrations.AlterField(
            model_name="reportetragamonedas",
            name="voucher_in_inicio",
            field=models.TextField(verbose_name="Voucher In (Inicio)"),
        ),
        migrations.AlterField(
            model_name="reportetragamonedas",
            name="voucher_out_cierre",
            field=models.TextField(verbose_name="Voucher Out (Cierre)"),
        ),
        migrations.AlterField(
            model_name="reportetragamonedas",
            name="voucher_out_inicio",
            field=models.TextField(verbose_name="Voucher Out (Inicio)"),
        ),
    ]
